name: User First Interaction

on:
  issues:
    types: [opened]
  pull_request:
    branches: [main]
    types: [opened]

jobs:
  check_for_first_interaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/first-interaction@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Hello! Thank you for filing an issue.

            If this is a bug report, please include relevant logs and screenshots to help us debug the problem.
            
            If you're looking to interact with everyone in the community, consider looking at our discussions page [here](https://github.com/orgs/TheRadixHub/discussions).
          pr-message: |
            Hello! Thank you for your contribution.
            
            Before submitting this pull request, please make sure you are using the right template!

            If you are fixing a bug, please reference the issue number in the description.
            If you are implementing a feature request, please check if there isn't already an open pr for it!